In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [8]:
data_path = './data/'
rf_data_list = os.listdir(data_path+'rf_data/')

rf_list = []

for rf in rf_data_list:
    rf_list.append(rf.split('.')[0])
    
for rf in rf_list:
    globals()[f'data_{rf}'] = pd.read_csv(data_path+'rf_data/'+rf+'.csv')

In [10]:
water_data_list = os.listdir(data_path+'water_data/')

water_list = []

for water in water_data_list:
    water_list.append(water.split('.')[0])
    
for water in water_list:
    globals()[f'water_{water}'] = pd.read_csv(data_path+'water_data/'+water+'.csv')

,ymdhm,swl,inf,sfw,ecpc,tototf,tide_level,wl_1018662,fw_1018662,wl_1018680,fw_1018680,wl_1018683,fw_1018683,wl_1019630,fw_1019630
0,2012-05-01 00:00,24.800,555.0,219.07,24.93,555.0,445.0,310.7,469.05,300.2,0.0,290.0,729.80,275.3,540.18
1,2012-05-01 00:10,24.794,464.6,218.86,25.15,562.9,449.0,314.7,498.00,300.2,0.0,290.0,731.48,275.3,540.18
2,2012-05-01 00:20,24.789,478.1,218.69,25.31,576.4,451.0,313.7,490.68,301.2,0.0,290.0,726.42,275.3,540.18
3,2012-05-01 00:30,24.789,464.8,218.69,25.31,563.1,452.0,311.7,476.21,301.2,0.0,290.0,726.42,276.3,552.17
4,2012-05-01 00:40,24.789,478.1,218.69,25.31,576.4,450.0,311.7,476.21,301.2,0.0,291.0,707.17,277.3,564.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26491,2012-10-31 23:10,25.250,270.2,235.01,8.99,270.2,300.0,372.7,1018.67,364.2,0.0,365.0,1395.30,351.3,1837.11
26492,2012-10-31 23:20,25.250,264.1,235.01,8.99,264.1,286.0,365.7,945.75,359.2,0.0,362.0,1154.21,350.3,1814.92
26493,2012-10-31 23:30,25.250,257.9,235.01,8.99,257.9,273.0,362.7,915.35,356.2,0.0,359.0,968.58,349.3,1792.88
26494,2012-10-31 23:40,25.250,264.1,235.01,8.99,264.1,261.0,355.7,846.39,352.2,0.0,356.0,776.99,346.3,1727.56
26495,2012-10-31 23:50,25.250,270.2,235.03,8.97,270.2,249.0,356.7,856.07,349.2,0.0,353.0,583.20,343.3,1663.48